import Config

# Configure your database
config :broker, Broker.Repo,
  url: System.get_env("DATABASE_URL") || "ecto://postgres:password@localhost/broker_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :broker, BrokerWeb.Endpoint,
  # Bind to 0.0.0.0 to expose the server to the docker host machine.
  # This makes make the service accessible from any network interface.
  # Change to `ip: {127, 0, 0, 1}` to allow access only from the server machine.
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "z2OC9lIY8wyhZpwRklgI9QRVlIkRdVy39OugyPWN1q+/lo+Q+Crn5pXuPDkzjWib",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :broker, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Dev-only fallback secrets (NEVER use these in production)
config :broker,
  jwt_secret: "dev_only_jwt_secret_key_do_not_use_in_production_1234567890",
  phone_hash_secret: "dev_only_phone_hash_secret_do_not_use_in_production",
  otp_sender_email: "securechat.dev@gmail.com"

# In dev, use Swoosh Local adapter (emails printed to terminal, viewable at /dev/mailbox)
# config :broker, Broker.Mailer,
#   adapter: Swoosh.Adapters.Local

config :swoosh, :api_client, false
